openapi: 3.0.0
info:
  version: '1.0'
  title: LiabAPI
  description: API de livres crée dans le cours de Service Web
servers: 
  - url: http://localhost/ServiceWeb/LiabAPI
paths:
  /books:
    get:
      tags:
        - Livre
      summary: Affiche la liste de tous les livres.
      responses:
        '200': 
          description: Un tableau de livres
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livres'
  /books/{id}:
    get:
      tags:
        - Livre
      summary: Affiche un livre selon son id.
      parameters:
        - name: id
          in: path
          required: true
          description: Le id du livre à afficher
          schema:
            type: integer
      responses:
        '200': 
          description: Le livre à afficher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livre'
components:
  schemas:
    Livre:
      type: object
      required:
        - genreId
        - titre
        - isbn
      properties:
        id:
          type: integer
          format: int64
        genreId:
          type: integer
          format: int64
        titre:
          type: string
        isbn:
          type: string
      example:
          id: 1
          genreId : 1
          titre: Fondation
          isbn: '9782070463619'
    Livres:
      type: array
      items:
        $ref: '#/components/schemas/Livre'